apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  PING_IDENTITY_PASSWORD: "2FederateM0re"
  #
  # PingFederate
  #
  PF_LOG_LEVEL: DEBUG
  PF_USER_PWD: 2FederateM0re
  PF_ADMIN_HOSTNAME: pingfederate-{{your eks namespace}}.ping-devops.com
  PF_ADMIN_PORT: "443"
  PF_ADMIN_MODE: "OIDC"
  # Used by PD DelAdmin Template
  PF_BASE_URL: "https://poc-hines.ping-eng.com"
  #
  # PD User Base DN
  #
  USER_BASE_DN: dc=customer360.com
  MAX_HEAP_SIZE: 768m
  #
  # PingCentral
  #
  MYSQL_PASSWORD: 2Federate
  MYSQL_ROOT_PASSWORD: 2Federate
  MYSQL_USER: root
  PING_CENTRAL_BLIND_TRUST: "true"
  PING_CENTRAL_OIDC_ENABLED: "true"
  PING_CENTRAL_VERIFY_HOSTNAME: "false"
  PING_CENTRAL_LOG_LEVEL: DEBUG
  #
  # Admin Console OIDC
  #
  # P14C \ Compass
  ADMIN_CLIENT_ID: "dc44d980-41f6-4c02-a2ed-ec162c431a9e"
  ADMIN_CLIENT_SECRET: "zU.J9NtSwW80SckIRIxVOzEzH7GELCzqtn.Ibpsn9yw6N24u8H-jm85DG7NSjx7q"
  ADMIN_CLIENT_ISSUER: "https://sso.anycompanyonline.net/as/"
  #
  # PF OIDC doesn't use .well-known to configure...
  #
  ADMIN_CLIENT_AUTHZ: "https://sso.anycompanyonline.net/as/authorize"
  ADMIN_CLIENT_TOKEN: "https://sso.anycompanyonline.net/as/token"
  ADMIN_CLIENT_USERINFO: "https://sso.anycompanyonline.net/as/userinfo"
  ADMIN_CLIENT_LOGOFF: "https://sso.anycompanyonline.net/as/signoff"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pingaccess-env-vars
  name: env-vars
---
apiVersion: v1
data:
  postman_vars.json: |
    {
        "id": "40199d03-d15c-47e4-b502-8b62f98479d1",
        "name": "Solution-Customer360",
        "values": [
            {
                "key": "pfBaseURL",
                "value": "poc-hines.ping-eng.com",
                "enabled": true
            },
            {
                "key": "pingIdSdk",
                "value": "#Auto-Generated from PingOne, downloaded by id=[929572] email=[patrickhines+365@pingidentity.com]\n#Thu Apr 09 18:42:03 MDT 2020\napi_key=ZmNiMTg1OWUtODBjZi00YTA2LTg4ZTItNGMxZjEwZTBmMjJl\ntoken=4321628f23af4bdfa1d0eb0a5db2d13f\npingidsdk_url=https://sdk.pingid.com/pingid\naccount_id=1454018c-4903-4291-a52b-68de8cce2aac,
                "enabled": true
            },
            {
                "key": "sdkAppId",
                "value": "e0f38195-8f32-4ba9-b59b-03dcab1b791e",
                "enabled": true
            },
    	    {
    	        "key": "paVirtualHost",
    	        "value": "poc-hines.ping-eng.com",
    	        "enabled": true
    	    },
            {
    	        "key": "pingCentralHost",
    	        "value": "pingcentral-{{your eks namespace}}.ping-devops.com",
    	        "enabled": true
            }
        ],
        "_postman_variable_scope": "environment"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: pingconfig
  name: pingconfig-cm0
